"""The RootIQ agent roster — single source of truth for what each agent is for.

Used by GET /api/agents (UI) and cross-checked against docs/AGENTS.md by the test-suite.
"""
from .base import AgentSpec

SPECS: dict[str, AgentSpec] = {
    s.id: s
    for s in [
        AgentSpec(
            id="orchestrator",
            name="Orchestrator",
            name_ar="المنسّق",
            layer="supervisor",
            autonomy="coordinate",
            mission="Runs the investigation pipeline in a fixed order, applies per-agent timeouts and fallbacks, and hands the case to the human.",
            mission_ar="يشغّل خط التحقيق بترتيب ثابت، يطبّق مهلة وبدائل لكل وكيل، ثم يسلّم الحالة للمهندس.",
            benefit="One agent failing (slow LLM, missing model file) never blocks the incident: the pipeline degrades instead of stopping, and the whole path is traceable.",
            benefit_ar="فشل أي وكيل (LLM بطيء، ملف نموذج مفقود) لا يوقف الحادثة: الخط يتدهور بأمان بدل أن يتوقف، والمسار كله قابل للتتبع.",
            inputs=("incident with symptoms",),
            outputs=("Investigation result", "trace steps", "hand-off to human"),
            tools=("all agents (call only)",),
            needs=("Agent runtime", "TraceStore", "agent_timeout_s setting"),
            guardrails=(
                "Cannot approve or execute anything itself",
                "Per-agent timeout (AGENT_TIMEOUT_S)",
                "Falls back to deterministic output on any agent error",
            ),
            can_disable=False,
        ),
        AgentSpec(
            id="telemetry",
            name="Telemetry Agent",
            name_ar="وكيل القياسات",
            layer="perception",
            autonomy="observe",
            mission="Validates every incoming event (finite, in range, right unit, not duplicated) and tracks freshness per source.",
            mission_ar="يتحقق من كل حدث وارد (رقم صالح، ضمن المدى، وحدة صحيحة، غير مكرر) ويتابع حداثة كل مصدر.",
            benefit="Bad or stale data is caught before it becomes a false incident; RCA is told when a source has gone silent instead of trusting old numbers.",
            benefit_ar="البيانات السيئة أو القديمة تُكتشف قبل أن تتحول إلى حادثة كاذبة، والـRCA يعرف متى صمت مصدر ما بدل الوثوق بأرقام قديمة.",
            inputs=("normalized Event",),
            outputs=("quality flags", "freshness map", "quality score"),
            tools=("pydantic schema", "per-metric unit/range table"),
            needs=("Event schema", "metric catalogue (units and ranges)"),
            guardrails=("Rejects non-finite values (422)", "Never modifies event values", "Flags, does not silently drop"),
        ),
        AgentSpec(
            id="detection",
            name="Detection Agent",
            name_ar="وكيل الكشف",
            layer="perception",
            autonomy="observe",
            mission="Turns metric streams into anomalies: static thresholds first, EWMA z-score to amplify, Isolation Forest as supporting evidence only.",
            mission_ar="يحوّل تدفق المقاييس إلى شذوذ: عتبات ثابتة أولًا، وz-score لتضخيمها، وIsolation Forest كدليل داعم فقط.",
            benefit="Detects a fault in about a second without any training data, and the multivariate model can only add evidence — it can never invent a root cause.",
            benefit_ar="يكتشف العطل خلال ثانية تقريبًا بدون بيانات تدريب، والنموذج متعدد المتغيرات يضيف دليلًا فقط ولا يخترع سببًا جذريًا.",
            inputs=("metric samples",),
            outputs=("Anomaly", "raw alert level", "multivariate score"),
            tools=("Baseline (EWMA)", "static thresholds", "IsolationForest (optional)"),
            needs=("thresholds.py", "warm-up of ~20 healthy samples", "data/models/iforest.joblib (optional)"),
            guardrails=("Baseline learning freezes during an anomaly", "Static gate before z-score to avoid false incidents"),
            can_disable=False,
        ),
        AgentSpec(
            id="topology",
            name="Topology Agent",
            name_ar="وكيل الطوبولوجيا",
            layer="reasoning",
            autonomy="observe",
            mission="Owns the dependency graph: which services ride which links, what is upstream/downstream, the blast radius of any element, and drift against CDP/LLDP.",
            mission_ar="يملك رسم الاعتماديات: أي خدمة تمر عبر أي رابط، ما هو upstream/downstream، ونطاق تأثر أي عنصر، والانحراف عن CDP/LLDP.",
            benefit="Answers 'what breaks if this link is slow?' from the graph, not from a guess — and makes the map highlight the cause path and the impact path.",
            benefit_ar="يجيب «ماذا ينكسر لو بطؤ هذا الرابط؟» من الرسم لا من التخمين، ويجعل الخريطة تبرز مسار السبب ومسار التأثر.",
            inputs=("entity ids", "observed neighbours (CDP/LLDP)"),
            outputs=("affected services", "impact path", "cause path", "drift report"),
            tools=("NetworkX graph", "configs/topology.json"),
            needs=("configs/topology.json", "vantage point defined", "NetworkX"),
            guardrails=("Read-only", "Unknown ids are reported, never invented"),
            can_disable=False,
        ),
        AgentSpec(
            id="correlation",
            name="Correlation Agent",
            name_ar="وكيل الربط",
            layer="reasoning",
            autonomy="observe",
            mission="Collapses an alert storm into one incident using topology relatedness and a time window, and measures the noise reduction.",
            mission_ar="يطوي عاصفة التنبيهات في حادثة واحدة باستخدام العلاقة الطوبولوجية ونافذة زمنية، ويقيس نسبة تقليل الضجيج.",
            benefit="The engineer sees one incident instead of dozens of alerts (about 96% less noise in the measured runs).",
            benefit_ar="المهندس يرى حادثة واحدة بدل عشرات التنبيهات (نحو 96% تقليل ضجيج في التجارب المقاسة).",
            inputs=("Anomaly", "open incidents"),
            outputs=("incident assignment", "noise reduction ratio"),
            tools=("Correlator (graph relatedness)", "120 s time window"),
            needs=("Topology Agent graph", "open-incident list"),
            guardrails=("Only merges symptoms that are topologically related", "Window bounded to 120 s"),
            can_disable=False,
        ),
        AgentSpec(
            id="rca",
            name="RCA Agent",
            name_ar="وكيل السبب الجذري",
            layer="reasoning",
            autonomy="advise",
            mission="Ranks candidate root causes with a weighted, explainable score and can answer 'why not X?'.",
            mission_ar="يرتّب الأسباب الجذرية المرشحة بدرجة موزونة قابلة للتفسير، ويجيب عن «لماذا ليس X؟».",
            benefit="Top-3 causes with evidence and a confidence number; if confidence is low it says more investigation is needed instead of pretending certainty.",
            benefit_ar="أفضل 3 أسباب مع الأدلة ونسبة ثقة؛ وإذا انخفضت الثقة يقول إن التحقيق مطلوب بدل ادعاء اليقين.",
            inputs=("anomalies", "affected services", "topology graph", "history"),
            outputs=("ranked Candidate list", "confidence", "why-not explanation"),
            tools=("rank() with 5 weighted components", "upstream suppression"),
            needs=("Topology graph", "History (historical_support)", "detector anomalies"),
            guardrails=("Deterministic — no LLM in the ranking", "Confidence < 55% flags needs-investigation"),
            can_disable=False,
        ),
        AgentSpec(
            id="explanation",
            name="Explanation Agent",
            name_ar="وكيل الشرح",
            layer="reasoning",
            autonomy="advise",
            mission="Writes the incident summary in English and Arabic from measured facts; an LLM may reword it only if every number is grounded.",
            mission_ar="يكتب ملخص الحادثة بالعربية والإنجليزية من الحقائق المقاسة؛ والـLLM قد يعيد الصياغة فقط إذا كانت كل الأرقام مؤسَّسة على القياسات.",
            benefit="Readable Arabic/English explanation for the NOC with zero hallucinated numbers.",
            benefit_ar="شرح مقروء بالعربية والإنجليزية للـNOC بدون أي رقم مختلق.",
            inputs=("root-cause facts",),
            outputs=("explanation {en, ar, source}",),
            tools=("bilingual templates", "grounded() number guard", "LLM client (optional)"),
            needs=("Templates", "LLM key only if LLM_ENABLED=1"),
            guardrails=("Any number absent from facts -> LLM text rejected", "Template is the fallback"),
            uses_llm=True,
        ),
        AgentSpec(
            id="knowledge",
            name="Knowledge Agent (RAG)",
            name_ar="وكيل المعرفة (RAG)",
            layer="knowledge",
            autonomy="observe",
            mission="Indexes project docs, topology, playbooks, lab configs (redacted), resolved incidents and postmortems, and retrieves cited passages.",
            mission_ar="يفهرس وثائق المشروع والطوبولوجيا وكتيبات المعالجة وإعدادات المختبر (بعد حجب الأسرار) والحوادث المحلولة وتقارير ما بعد الحادثة، ويسترجع مقاطع موثّقة بالمصدر.",
            benefit="Gives the engineer past similar incidents and the exact runbook step, and gives the Copilot grounded context with citations.",
            benefit_ar="يعطي المهندس حوادث سابقة مشابهة وخطوة الـrunbook المطلوبة، ويعطي المساعد سياقًا موثّقًا بالمصادر.",
            inputs=("query text", "resolved incidents"),
            outputs=("ranked passages with source + score", "similar incidents"),
            tools=("TF-IDF index (scikit-learn)", "markdown chunker", "secret redactor"),
            needs=("docs/ folder", "configs/topology.json", "scikit-learn"),
            guardrails=("Secrets in lab configs are redacted before indexing", "Injection-looking passages are flagged", "Returns nothing below the minimum score"),
        ),
        AgentSpec(
            id="copilot",
            name="Copilot Agent",
            name_ar="وكيل المساعد",
            layer="knowledge",
            autonomy="advise",
            mission="Answers the engineer's questions (status, why, why-not, impact, actions, audit, KPIs, docs) in Arabic or English, with citations.",
            mission_ar="يجيب عن أسئلة المهندس (الحالة، لماذا، لماذا ليس، التأثر، الإجراءات، السجل، المؤشرات، الوثائق) بالعربية أو الإنجليزية مع المصادر.",
            benefit="Ask instead of clicking through panels — and every claim is tied to a measured fact or a cited document.",
            benefit_ar="اسأل بدل التنقل بين اللوحات — وكل ادعاء مرتبط بقياس فعلي أو بوثيقة مذكورة المصدر.",
            inputs=("question", "optional incident id", "language"),
            outputs=("answer", "sources", "facts", "confidence"),
            tools=("read-only state readers", "Knowledge Agent", "LLM client (optional)"),
            needs=("Knowledge Agent index", "incident/topology/audit readers", "LLM key only if enabled"),
            guardrails=(
                "Strictly read-only: no approve/reject/execute tool exists",
                "Retrieved text is data, never instructions",
                "LLM answer must cite sources and use only grounded numbers",
                "Says 'not found' instead of guessing",
            ),
            uses_llm=True,
        ),
        AgentSpec(
            id="remediation",
            name="Remediation Planner",
            name_ar="مخطِّط المعالجة",
            layer="action",
            autonomy="advise",
            mission="Selects a whitelisted playbook for the root cause and produces a full plan: steps, risk, rollback, verification criteria and alternatives.",
            mission_ar="يختار كتيب معالجة ضمن القائمة البيضاء للسبب الجذري ويبني خطة كاملة: خطوات، مخاطر، تراجع، معايير تحقق، وبدائل.",
            benefit="The engineer approves a concrete, reversible plan rather than a vague suggestion.",
            benefit_ar="المهندس يوافق على خطة محددة وقابلة للتراجع بدل اقتراح غامض.",
            inputs=("incident root cause", "impact path"),
            outputs=("action with plan {steps, rollback, verification, riskFactors}",),
            tools=("playbook catalogue",),
            needs=("playbooks.py", "root cause kind"),
            guardrails=("Only catalogue playbooks — never free-form commands", "Every plan requires human approval"),
            can_disable=False,
        ),
        AgentSpec(
            id="guardrail",
            name="Guardrail Agent",
            name_ar="وكيل الحماية",
            layer="governance",
            autonomy="coordinate",
            mission="Enforces policy at every stage: human approval only, whitelist, valid state, execution switch, rate limit and lab isolation.",
            mission_ar="يطبّق السياسات في كل مرحلة: موافقة بشرية فقط، قائمة بيضاء، حالة صالحة، مفتاح التنفيذ، حد المعدل، وعزل المختبر.",
            benefit="Makes 'nothing runs without an engineer' a hard rule in code, not a convention — and logs every denial.",
            benefit_ar="يجعل «لا شيء يُنفَّذ بدون مهندس» قاعدة صارمة في الكود لا مجرد عرف، ويسجل كل رفض.",
            inputs=("action", "incident", "decider", "stage"),
            outputs=("verdict {allowed, checks, warnings}",),
            tools=("policy list", "AuditLog"),
            needs=("Settings (execution switch, rate limit, lab URL)", "AuditLog"),
            guardrails=("Cannot be disabled", "Agents and system accounts can never approve"),
            can_disable=False,
        ),
        AgentSpec(
            id="execution",
            name="Execution Agent",
            name_ar="وكيل التنفيذ",
            layer="action",
            autonomy="act_with_approval",
            mission="Executes an already-approved playbook through the whitelist-only lab agent (or the simulator); becomes a dry run when execution is switched off.",
            mission_ar="ينفّذ كتيبًا تمت الموافقة عليه عبر وكيل المختبر المحصور بقائمة بيضاء (أو المحاكي)، ويتحول إلى تشغيل تجريبي عند إيقاف مفتاح التنفيذ.",
            benefit="The only component that touches the lab, and it refuses to run without a fresh Guardrail verdict for that exact action.",
            benefit_ar="المكوّن الوحيد الذي يلمس المختبر، ويرفض العمل بدون حكم Guardrail حديث لهذا الإجراء بالذات.",
            inputs=("approved action", "Guardrail verdict"),
            outputs=("execution result {executed, dryRun, output}",),
            tools=("lab_client (whitelisted endpoints)", "Simulator.remediate()"),
            needs=("Lab agent reachable (live mode)", "LAB_AGENT_TOKEN"),
            guardrails=("Needs approvalStatus=approved AND verdict.allowed", "No shell, no free-form commands", "Cannot be disabled"),
            can_disable=False,
        ),
        AgentSpec(
            id="verification",
            name="Verification Agent",
            name_ar="وكيل التحقق",
            layer="action",
            autonomy="observe",
            mission="After remediation, checks the playbook's success criteria against live metrics and records verified / partial / unverified.",
            mission_ar="بعد المعالجة يفحص معايير نجاح الكتيب على المقاييس الحية ويسجل: متحقَّق / جزئي / غير متحقَّق.",
            benefit="Recovery is proven with numbers, not assumed — and a failed fix is surfaced for rollback instead of being silently closed.",
            benefit_ar="التعافي يُثبَت بالأرقام لا يُفترض، والإصلاح الفاشل يُعرض للتراجع بدل إغلاقه بصمت.",
            inputs=("incident", "plan.verification criteria", "live state"),
            outputs=("verification {status, checks}",),
            tools=("StateStore reader",),
            needs=("StateStore", "plan.verification criteria"),
            guardrails=("Advisory: never blocks or triggers changes by itself",),
        ),
        AgentSpec(
            id="learning",
            name="Learning & Postmortem Agent",
            name_ar="وكيل التعلّم وما بعد الحادثة",
            layer="learning",
            autonomy="advise",
            mission="Closes the incident: updates historical support, writes a postmortem (timeline, decision, KPIs, improvements) and feeds it back into the knowledge index.",
            mission_ar="يغلق الحادثة: يحدّث الدعم التاريخي، يكتب تقرير ما بعد الحادثة (خط زمني، قرار، مؤشرات، تحسينات)، ويغذّي به فهرس المعرفة.",
            benefit="Every incident makes the next one faster: confidence rises for repeat causes and the team gets a ready postmortem.",
            benefit_ar="كل حادثة تجعل التالية أسرع: ترتفع الثقة للأسباب المتكررة ويحصل الفريق على تقرير جاهز.",
            inputs=("resolved incident", "audit trail", "trace"),
            outputs=("postmortem (markdown + json)", "history update", "knowledge entry"),
            tools=("History", "Knowledge Agent", "filesystem (data/postmortems)"),
            needs=("History file", "writable data/ folder"),
            guardrails=("Writes only to data/postmortems", "Does not change thresholds or weights automatically"),
        ),
    ]
}

ORDER = list(SPECS)

# Investigation pipeline shown in the UI (stage -> agents) and used by docs.
FLOW = [
    {"stage": "perceive", "agents": ["telemetry", "detection"]},
    {"stage": "correlate", "agents": ["correlation", "topology"]},
    {"stage": "diagnose", "agents": ["rca", "explanation", "knowledge"]},
    {"stage": "plan", "agents": ["remediation", "guardrail"]},
    {"stage": "human", "agents": []},
    {"stage": "act", "agents": ["guardrail", "execution"]},
    {"stage": "close", "agents": ["verification", "learning"]},
]
EDGES = [
    ["telemetry", "detection"],
    ["detection", "correlation"],
    ["topology", "correlation"],
    ["correlation", "rca"],
    ["topology", "rca"],
    ["rca", "explanation"],
    ["rca", "knowledge"],
    ["rca", "remediation"],
    ["remediation", "guardrail"],
    ["guardrail", "execution"],
    ["execution", "verification"],
    ["verification", "learning"],
    ["learning", "knowledge"],
    ["knowledge", "copilot"],
]
